package shadersmod.client;

import java.util.*;
import java.nio.*;

public class SMath
{
    static void invertMat4(final float[] lllllllllllllllIlllllIIIllIIIlIl, final float[] lllllllllllllllIlllllIIIllIIIlII) {
        lllllllllllllllIlllllIIIllIIIlIl[0] = lllllllllllllllIlllllIIIllIIIlII[5] * lllllllllllllllIlllllIIIllIIIlII[10] * lllllllllllllllIlllllIIIllIIIlII[15] - lllllllllllllllIlllllIIIllIIIlII[5] * lllllllllllllllIlllllIIIllIIIlII[11] * lllllllllllllllIlllllIIIllIIIlII[14] - lllllllllllllllIlllllIIIllIIIlII[9] * lllllllllllllllIlllllIIIllIIIlII[6] * lllllllllllllllIlllllIIIllIIIlII[15] + lllllllllllllllIlllllIIIllIIIlII[9] * lllllllllllllllIlllllIIIllIIIlII[7] * lllllllllllllllIlllllIIIllIIIlII[14] + lllllllllllllllIlllllIIIllIIIlII[13] * lllllllllllllllIlllllIIIllIIIlII[6] * lllllllllllllllIlllllIIIllIIIlII[11] - lllllllllllllllIlllllIIIllIIIlII[13] * lllllllllllllllIlllllIIIllIIIlII[7] * lllllllllllllllIlllllIIIllIIIlII[10];
        lllllllllllllllIlllllIIIllIIIlIl[1] = -lllllllllllllllIlllllIIIllIIIlII[1] * lllllllllllllllIlllllIIIllIIIlII[10] * lllllllllllllllIlllllIIIllIIIlII[15] + lllllllllllllllIlllllIIIllIIIlII[1] * lllllllllllllllIlllllIIIllIIIlII[11] * lllllllllllllllIlllllIIIllIIIlII[14] + lllllllllllllllIlllllIIIllIIIlII[9] * lllllllllllllllIlllllIIIllIIIlII[2] * lllllllllllllllIlllllIIIllIIIlII[15] - lllllllllllllllIlllllIIIllIIIlII[9] * lllllllllllllllIlllllIIIllIIIlII[3] * lllllllllllllllIlllllIIIllIIIlII[14] - lllllllllllllllIlllllIIIllIIIlII[13] * lllllllllllllllIlllllIIIllIIIlII[2] * lllllllllllllllIlllllIIIllIIIlII[11] + lllllllllllllllIlllllIIIllIIIlII[13] * lllllllllllllllIlllllIIIllIIIlII[3] * lllllllllllllllIlllllIIIllIIIlII[10];
        lllllllllllllllIlllllIIIllIIIlIl[2] = lllllllllllllllIlllllIIIllIIIlII[1] * lllllllllllllllIlllllIIIllIIIlII[6] * lllllllllllllllIlllllIIIllIIIlII[15] - lllllllllllllllIlllllIIIllIIIlII[1] * lllllllllllllllIlllllIIIllIIIlII[7] * lllllllllllllllIlllllIIIllIIIlII[14] - lllllllllllllllIlllllIIIllIIIlII[5] * lllllllllllllllIlllllIIIllIIIlII[2] * lllllllllllllllIlllllIIIllIIIlII[15] + lllllllllllllllIlllllIIIllIIIlII[5] * lllllllllllllllIlllllIIIllIIIlII[3] * lllllllllllllllIlllllIIIllIIIlII[14] + lllllllllllllllIlllllIIIllIIIlII[13] * lllllllllllllllIlllllIIIllIIIlII[2] * lllllllllllllllIlllllIIIllIIIlII[7] - lllllllllllllllIlllllIIIllIIIlII[13] * lllllllllllllllIlllllIIIllIIIlII[3] * lllllllllllllllIlllllIIIllIIIlII[6];
        lllllllllllllllIlllllIIIllIIIlIl[3] = -lllllllllllllllIlllllIIIllIIIlII[1] * lllllllllllllllIlllllIIIllIIIlII[6] * lllllllllllllllIlllllIIIllIIIlII[11] + lllllllllllllllIlllllIIIllIIIlII[1] * lllllllllllllllIlllllIIIllIIIlII[7] * lllllllllllllllIlllllIIIllIIIlII[10] + lllllllllllllllIlllllIIIllIIIlII[5] * lllllllllllllllIlllllIIIllIIIlII[2] * lllllllllllllllIlllllIIIllIIIlII[11] - lllllllllllllllIlllllIIIllIIIlII[5] * lllllllllllllllIlllllIIIllIIIlII[3] * lllllllllllllllIlllllIIIllIIIlII[10] - lllllllllllllllIlllllIIIllIIIlII[9] * lllllllllllllllIlllllIIIllIIIlII[2] * lllllllllllllllIlllllIIIllIIIlII[7] + lllllllllllllllIlllllIIIllIIIlII[9] * lllllllllllllllIlllllIIIllIIIlII[3] * lllllllllllllllIlllllIIIllIIIlII[6];
        lllllllllllllllIlllllIIIllIIIlIl[4] = -lllllllllllllllIlllllIIIllIIIlII[4] * lllllllllllllllIlllllIIIllIIIlII[10] * lllllllllllllllIlllllIIIllIIIlII[15] + lllllllllllllllIlllllIIIllIIIlII[4] * lllllllllllllllIlllllIIIllIIIlII[11] * lllllllllllllllIlllllIIIllIIIlII[14] + lllllllllllllllIlllllIIIllIIIlII[8] * lllllllllllllllIlllllIIIllIIIlII[6] * lllllllllllllllIlllllIIIllIIIlII[15] - lllllllllllllllIlllllIIIllIIIlII[8] * lllllllllllllllIlllllIIIllIIIlII[7] * lllllllllllllllIlllllIIIllIIIlII[14] - lllllllllllllllIlllllIIIllIIIlII[12] * lllllllllllllllIlllllIIIllIIIlII[6] * lllllllllllllllIlllllIIIllIIIlII[11] + lllllllllllllllIlllllIIIllIIIlII[12] * lllllllllllllllIlllllIIIllIIIlII[7] * lllllllllllllllIlllllIIIllIIIlII[10];
        lllllllllllllllIlllllIIIllIIIlIl[5] = lllllllllllllllIlllllIIIllIIIlII[0] * lllllllllllllllIlllllIIIllIIIlII[10] * lllllllllllllllIlllllIIIllIIIlII[15] - lllllllllllllllIlllllIIIllIIIlII[0] * lllllllllllllllIlllllIIIllIIIlII[11] * lllllllllllllllIlllllIIIllIIIlII[14] - lllllllllllllllIlllllIIIllIIIlII[8] * lllllllllllllllIlllllIIIllIIIlII[2] * lllllllllllllllIlllllIIIllIIIlII[15] + lllllllllllllllIlllllIIIllIIIlII[8] * lllllllllllllllIlllllIIIllIIIlII[3] * lllllllllllllllIlllllIIIllIIIlII[14] + lllllllllllllllIlllllIIIllIIIlII[12] * lllllllllllllllIlllllIIIllIIIlII[2] * lllllllllllllllIlllllIIIllIIIlII[11] - lllllllllllllllIlllllIIIllIIIlII[12] * lllllllllllllllIlllllIIIllIIIlII[3] * lllllllllllllllIlllllIIIllIIIlII[10];
        lllllllllllllllIlllllIIIllIIIlIl[6] = -lllllllllllllllIlllllIIIllIIIlII[0] * lllllllllllllllIlllllIIIllIIIlII[6] * lllllllllllllllIlllllIIIllIIIlII[15] + lllllllllllllllIlllllIIIllIIIlII[0] * lllllllllllllllIlllllIIIllIIIlII[7] * lllllllllllllllIlllllIIIllIIIlII[14] + lllllllllllllllIlllllIIIllIIIlII[4] * lllllllllllllllIlllllIIIllIIIlII[2] * lllllllllllllllIlllllIIIllIIIlII[15] - lllllllllllllllIlllllIIIllIIIlII[4] * lllllllllllllllIlllllIIIllIIIlII[3] * lllllllllllllllIlllllIIIllIIIlII[14] - lllllllllllllllIlllllIIIllIIIlII[12] * lllllllllllllllIlllllIIIllIIIlII[2] * lllllllllllllllIlllllIIIllIIIlII[7] + lllllllllllllllIlllllIIIllIIIlII[12] * lllllllllllllllIlllllIIIllIIIlII[3] * lllllllllllllllIlllllIIIllIIIlII[6];
        lllllllllllllllIlllllIIIllIIIlIl[7] = lllllllllllllllIlllllIIIllIIIlII[0] * lllllllllllllllIlllllIIIllIIIlII[6] * lllllllllllllllIlllllIIIllIIIlII[11] - lllllllllllllllIlllllIIIllIIIlII[0] * lllllllllllllllIlllllIIIllIIIlII[7] * lllllllllllllllIlllllIIIllIIIlII[10] - lllllllllllllllIlllllIIIllIIIlII[4] * lllllllllllllllIlllllIIIllIIIlII[2] * lllllllllllllllIlllllIIIllIIIlII[11] + lllllllllllllllIlllllIIIllIIIlII[4] * lllllllllllllllIlllllIIIllIIIlII[3] * lllllllllllllllIlllllIIIllIIIlII[10] + lllllllllllllllIlllllIIIllIIIlII[8] * lllllllllllllllIlllllIIIllIIIlII[2] * lllllllllllllllIlllllIIIllIIIlII[7] - lllllllllllllllIlllllIIIllIIIlII[8] * lllllllllllllllIlllllIIIllIIIlII[3] * lllllllllllllllIlllllIIIllIIIlII[6];
        lllllllllllllllIlllllIIIllIIIlIl[8] = lllllllllllllllIlllllIIIllIIIlII[4] * lllllllllllllllIlllllIIIllIIIlII[9] * lllllllllllllllIlllllIIIllIIIlII[15] - lllllllllllllllIlllllIIIllIIIlII[4] * lllllllllllllllIlllllIIIllIIIlII[11] * lllllllllllllllIlllllIIIllIIIlII[13] - lllllllllllllllIlllllIIIllIIIlII[8] * lllllllllllllllIlllllIIIllIIIlII[5] * lllllllllllllllIlllllIIIllIIIlII[15] + lllllllllllllllIlllllIIIllIIIlII[8] * lllllllllllllllIlllllIIIllIIIlII[7] * lllllllllllllllIlllllIIIllIIIlII[13] + lllllllllllllllIlllllIIIllIIIlII[12] * lllllllllllllllIlllllIIIllIIIlII[5] * lllllllllllllllIlllllIIIllIIIlII[11] - lllllllllllllllIlllllIIIllIIIlII[12] * lllllllllllllllIlllllIIIllIIIlII[7] * lllllllllllllllIlllllIIIllIIIlII[9];
        lllllllllllllllIlllllIIIllIIIlIl[9] = -lllllllllllllllIlllllIIIllIIIlII[0] * lllllllllllllllIlllllIIIllIIIlII[9] * lllllllllllllllIlllllIIIllIIIlII[15] + lllllllllllllllIlllllIIIllIIIlII[0] * lllllllllllllllIlllllIIIllIIIlII[11] * lllllllllllllllIlllllIIIllIIIlII[13] + lllllllllllllllIlllllIIIllIIIlII[8] * lllllllllllllllIlllllIIIllIIIlII[1] * lllllllllllllllIlllllIIIllIIIlII[15] - lllllllllllllllIlllllIIIllIIIlII[8] * lllllllllllllllIlllllIIIllIIIlII[3] * lllllllllllllllIlllllIIIllIIIlII[13] - lllllllllllllllIlllllIIIllIIIlII[12] * lllllllllllllllIlllllIIIllIIIlII[1] * lllllllllllllllIlllllIIIllIIIlII[11] + lllllllllllllllIlllllIIIllIIIlII[12] * lllllllllllllllIlllllIIIllIIIlII[3] * lllllllllllllllIlllllIIIllIIIlII[9];
        lllllllllllllllIlllllIIIllIIIlIl[10] = lllllllllllllllIlllllIIIllIIIlII[0] * lllllllllllllllIlllllIIIllIIIlII[5] * lllllllllllllllIlllllIIIllIIIlII[15] - lllllllllllllllIlllllIIIllIIIlII[0] * lllllllllllllllIlllllIIIllIIIlII[7] * lllllllllllllllIlllllIIIllIIIlII[13] - lllllllllllllllIlllllIIIllIIIlII[4] * lllllllllllllllIlllllIIIllIIIlII[1] * lllllllllllllllIlllllIIIllIIIlII[15] + lllllllllllllllIlllllIIIllIIIlII[4] * lllllllllllllllIlllllIIIllIIIlII[3] * lllllllllllllllIlllllIIIllIIIlII[13] + lllllllllllllllIlllllIIIllIIIlII[12] * lllllllllllllllIlllllIIIllIIIlII[1] * lllllllllllllllIlllllIIIllIIIlII[7] - lllllllllllllllIlllllIIIllIIIlII[12] * lllllllllllllllIlllllIIIllIIIlII[3] * lllllllllllllllIlllllIIIllIIIlII[5];
        lllllllllllllllIlllllIIIllIIIlIl[11] = -lllllllllllllllIlllllIIIllIIIlII[0] * lllllllllllllllIlllllIIIllIIIlII[5] * lllllllllllllllIlllllIIIllIIIlII[11] + lllllllllllllllIlllllIIIllIIIlII[0] * lllllllllllllllIlllllIIIllIIIlII[7] * lllllllllllllllIlllllIIIllIIIlII[9] + lllllllllllllllIlllllIIIllIIIlII[4] * lllllllllllllllIlllllIIIllIIIlII[1] * lllllllllllllllIlllllIIIllIIIlII[11] - lllllllllllllllIlllllIIIllIIIlII[4] * lllllllllllllllIlllllIIIllIIIlII[3] * lllllllllllllllIlllllIIIllIIIlII[9] - lllllllllllllllIlllllIIIllIIIlII[8] * lllllllllllllllIlllllIIIllIIIlII[1] * lllllllllllllllIlllllIIIllIIIlII[7] + lllllllllllllllIlllllIIIllIIIlII[8] * lllllllllllllllIlllllIIIllIIIlII[3] * lllllllllllllllIlllllIIIllIIIlII[5];
        lllllllllllllllIlllllIIIllIIIlIl[12] = -lllllllllllllllIlllllIIIllIIIlII[4] * lllllllllllllllIlllllIIIllIIIlII[9] * lllllllllllllllIlllllIIIllIIIlII[14] + lllllllllllllllIlllllIIIllIIIlII[4] * lllllllllllllllIlllllIIIllIIIlII[10] * lllllllllllllllIlllllIIIllIIIlII[13] + lllllllllllllllIlllllIIIllIIIlII[8] * lllllllllllllllIlllllIIIllIIIlII[5] * lllllllllllllllIlllllIIIllIIIlII[14] - lllllllllllllllIlllllIIIllIIIlII[8] * lllllllllllllllIlllllIIIllIIIlII[6] * lllllllllllllllIlllllIIIllIIIlII[13] - lllllllllllllllIlllllIIIllIIIlII[12] * lllllllllllllllIlllllIIIllIIIlII[5] * lllllllllllllllIlllllIIIllIIIlII[10] + lllllllllllllllIlllllIIIllIIIlII[12] * lllllllllllllllIlllllIIIllIIIlII[6] * lllllllllllllllIlllllIIIllIIIlII[9];
        lllllllllllllllIlllllIIIllIIIlIl[13] = lllllllllllllllIlllllIIIllIIIlII[0] * lllllllllllllllIlllllIIIllIIIlII[9] * lllllllllllllllIlllllIIIllIIIlII[14] - lllllllllllllllIlllllIIIllIIIlII[0] * lllllllllllllllIlllllIIIllIIIlII[10] * lllllllllllllllIlllllIIIllIIIlII[13] - lllllllllllllllIlllllIIIllIIIlII[8] * lllllllllllllllIlllllIIIllIIIlII[1] * lllllllllllllllIlllllIIIllIIIlII[14] + lllllllllllllllIlllllIIIllIIIlII[8] * lllllllllllllllIlllllIIIllIIIlII[2] * lllllllllllllllIlllllIIIllIIIlII[13] + lllllllllllllllIlllllIIIllIIIlII[12] * lllllllllllllllIlllllIIIllIIIlII[1] * lllllllllllllllIlllllIIIllIIIlII[10] - lllllllllllllllIlllllIIIllIIIlII[12] * lllllllllllllllIlllllIIIllIIIlII[2] * lllllllllllllllIlllllIIIllIIIlII[9];
        lllllllllllllllIlllllIIIllIIIlIl[14] = -lllllllllllllllIlllllIIIllIIIlII[0] * lllllllllllllllIlllllIIIllIIIlII[5] * lllllllllllllllIlllllIIIllIIIlII[14] + lllllllllllllllIlllllIIIllIIIlII[0] * lllllllllllllllIlllllIIIllIIIlII[6] * lllllllllllllllIlllllIIIllIIIlII[13] + lllllllllllllllIlllllIIIllIIIlII[4] * lllllllllllllllIlllllIIIllIIIlII[1] * lllllllllllllllIlllllIIIllIIIlII[14] - lllllllllllllllIlllllIIIllIIIlII[4] * lllllllllllllllIlllllIIIllIIIlII[2] * lllllllllllllllIlllllIIIllIIIlII[13] - lllllllllllllllIlllllIIIllIIIlII[12] * lllllllllllllllIlllllIIIllIIIlII[1] * lllllllllllllllIlllllIIIllIIIlII[6] + lllllllllllllllIlllllIIIllIIIlII[12] * lllllllllllllllIlllllIIIllIIIlII[2] * lllllllllllllllIlllllIIIllIIIlII[5];
        lllllllllllllllIlllllIIIllIIIlIl[15] = lllllllllllllllIlllllIIIllIIIlII[0] * lllllllllllllllIlllllIIIllIIIlII[5] * lllllllllllllllIlllllIIIllIIIlII[10] - lllllllllllllllIlllllIIIllIIIlII[0] * lllllllllllllllIlllllIIIllIIIlII[6] * lllllllllllllllIlllllIIIllIIIlII[9] - lllllllllllllllIlllllIIIllIIIlII[4] * lllllllllllllllIlllllIIIllIIIlII[1] * lllllllllllllllIlllllIIIllIIIlII[10] + lllllllllllllllIlllllIIIllIIIlII[4] * lllllllllllllllIlllllIIIllIIIlII[2] * lllllllllllllllIlllllIIIllIIIlII[9] + lllllllllllllllIlllllIIIllIIIlII[8] * lllllllllllllllIlllllIIIllIIIlII[1] * lllllllllllllllIlllllIIIllIIIlII[6] - lllllllllllllllIlllllIIIllIIIlII[8] * lllllllllllllllIlllllIIIllIIIlII[2] * lllllllllllllllIlllllIIIllIIIlII[5];
        final float lllllllllllllllIlllllIIIllIIIlll = lllllllllllllllIlllllIIIllIIIlII[0] * lllllllllllllllIlllllIIIllIIIlIl[0] + lllllllllllllllIlllllIIIllIIIlII[1] * lllllllllllllllIlllllIIIllIIIlIl[4] + lllllllllllllllIlllllIIIllIIIlII[2] * lllllllllllllllIlllllIIIllIIIlIl[8] + lllllllllllllllIlllllIIIllIIIlII[3] * lllllllllllllllIlllllIIIllIIIlIl[12];
        if (lllllllllllllllIlllllIIIllIIIlll != 0.0) {
            for (int lllllllllllllllIlllllIIIllIIIllI = 0; lllllllllllllllIlllllIIIllIIIllI < 16; ++lllllllllllllllIlllllIIIllIIIllI) {
                final int n = lllllllllllllllIlllllIIIllIIIllI;
                lllllllllllllllIlllllIIIllIIIlIl[n] /= lllllllllllllllIlllllIIIllIIIlll;
            }
        }
        else {
            Arrays.fill(lllllllllllllllIlllllIIIllIIIlIl, 0.0f);
        }
    }
    
    static void multiplyMat4xMat4(final float[] lllllllllllllllIlllllIIIlllIIIII, final float[] lllllllllllllllIlllllIIIllIllIlI, final float[] lllllllllllllllIlllllIIIllIllllI) {
        for (int lllllllllllllllIlllllIIIllIlllIl = 0; lllllllllllllllIlllllIIIllIlllIl < 4; ++lllllllllllllllIlllllIIIllIlllIl) {
            for (int lllllllllllllllIlllllIIIllIlllII = 0; lllllllllllllllIlllllIIIllIlllII < 4; ++lllllllllllllllIlllllIIIllIlllII) {
                lllllllllllllllIlllllIIIlllIIIII[4 * lllllllllllllllIlllllIIIllIlllIl + lllllllllllllllIlllllIIIllIlllII] = lllllllllllllllIlllllIIIllIllIlI[4 * lllllllllllllllIlllllIIIllIlllIl + 0] * lllllllllllllllIlllllIIIllIllllI[0 + lllllllllllllllIlllllIIIllIlllII] + lllllllllllllllIlllllIIIllIllIlI[4 * lllllllllllllllIlllllIIIllIlllIl + 1] * lllllllllllllllIlllllIIIllIllllI[4 + lllllllllllllllIlllllIIIllIlllII] + lllllllllllllllIlllllIIIllIllIlI[4 * lllllllllllllllIlllllIIIllIlllIl + 2] * lllllllllllllllIlllllIIIllIllllI[8 + lllllllllllllllIlllllIIIllIlllII] + lllllllllllllllIlllllIIIllIllIlI[4 * lllllllllllllllIlllllIIIllIlllIl + 3] * lllllllllllllllIlllllIIIllIllllI[12 + lllllllllllllllIlllllIIIllIlllII];
            }
        }
    }
    
    static void invertMat4FBFA(final FloatBuffer lllllllllllllllIlllllIIIlIllllIl, final FloatBuffer lllllllllllllllIlllllIIIlIlllIII, final float[] lllllllllllllllIlllllIIIlIlllIll, final float[] lllllllllllllllIlllllIIIlIlllIlI) {
        lllllllllllllllIlllllIIIlIlllIII.get(lllllllllllllllIlllllIIIlIlllIlI);
        invertMat4(lllllllllllllllIlllllIIIlIlllIll, lllllllllllllllIlllllIIIlIlllIlI);
        lllllllllllllllIlllllIIIlIllllIl.put(lllllllllllllllIlllllIIIlIlllIll);
    }
    
    static void multiplyMat4xVec4(final float[] lllllllllllllllIlllllIIIllIlIIII, final float[] lllllllllllllllIlllllIIIllIlIIlI, final float[] lllllllllllllllIlllllIIIllIIlllI) {
        lllllllllllllllIlllllIIIllIlIIII[0] = lllllllllllllllIlllllIIIllIlIIlI[0] * lllllllllllllllIlllllIIIllIIlllI[0] + lllllllllllllllIlllllIIIllIlIIlI[4] * lllllllllllllllIlllllIIIllIIlllI[1] + lllllllllllllllIlllllIIIllIlIIlI[8] * lllllllllllllllIlllllIIIllIIlllI[2] + lllllllllllllllIlllllIIIllIlIIlI[12] * lllllllllllllllIlllllIIIllIIlllI[3];
        lllllllllllllllIlllllIIIllIlIIII[1] = lllllllllllllllIlllllIIIllIlIIlI[1] * lllllllllllllllIlllllIIIllIIlllI[0] + lllllllllllllllIlllllIIIllIlIIlI[5] * lllllllllllllllIlllllIIIllIIlllI[1] + lllllllllllllllIlllllIIIllIlIIlI[9] * lllllllllllllllIlllllIIIllIIlllI[2] + lllllllllllllllIlllllIIIllIlIIlI[13] * lllllllllllllllIlllllIIIllIIlllI[3];
        lllllllllllllllIlllllIIIllIlIIII[2] = lllllllllllllllIlllllIIIllIlIIlI[2] * lllllllllllllllIlllllIIIllIIlllI[0] + lllllllllllllllIlllllIIIllIlIIlI[6] * lllllllllllllllIlllllIIIllIIlllI[1] + lllllllllllllllIlllllIIIllIlIIlI[10] * lllllllllllllllIlllllIIIllIIlllI[2] + lllllllllllllllIlllllIIIllIlIIlI[14] * lllllllllllllllIlllllIIIllIIlllI[3];
        lllllllllllllllIlllllIIIllIlIIII[3] = lllllllllllllllIlllllIIIllIlIIlI[3] * lllllllllllllllIlllllIIIllIIlllI[0] + lllllllllllllllIlllllIIIllIlIIlI[7] * lllllllllllllllIlllllIIIllIIlllI[1] + lllllllllllllllIlllllIIIllIlIIlI[11] * lllllllllllllllIlllllIIIllIIlllI[2] + lllllllllllllllIlllllIIIllIlIIlI[15] * lllllllllllllllIlllllIIIllIIlllI[3];
    }
}
